# This workflow validates the document for markup and examples.
name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    name: Build and Validate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2
    - name: Install dependencies
      run: bundle install

    - name: "Verify common files are consistent"
      run: |
        git remote add -f b https://github.com/w3c/json-ld-wg.git
        git remote update
        git diff --exit-code remotes/b/main -- common

    - name: Verify examples are consistent
      run: bundle exec rake test

    - name: Echidna Auto-publish WD
      uses: w3c/spec-prod@v2
      with:
        TOOLCHAIN: respec
        SOURCE: index.html
        VALIDATE_LINKS: false
        VALIDATE_MARKUP: true
        ACTIONS_STEP_DEBUG: true
        W3C_ECHIDNA_TOKEN: ${{ secrets.ECHIDNA_TOKEN }}
        #W3C_WG_DECISION_URL: https://www.w3.org/2023/04/20-rdf-star-minutes.html#r03
        W3C_BUILD_OVERRIDE: |
          specStatus: WD
          shortName: json-ld11-concepts
